/// Render a `vendor/bin/<tool>` PHP proxy. `rel_from_vendor` is the real binary's path
/// relative to the vendor dir (e.g. "phpunit/phpunit/phpunit"). The proxy exposes the
/// autoload path (some tools read `$_composer_autoload_path`) then includes the binary.
pub fn render_bin_proxy_php(rel_from_vendor: &str) -> String {
    let rel = rel_from_vendor.trim_start_matches('/');
    format!(
        "#!/usr/bin/env php\n<?php\n\n// @generated by phpm\n\n$_composer_autoload_path = __DIR__ . '/../autoload.php';\n$GLOBALS['_composer_autoload_path'] = $_composer_autoload_path;\n\ninclude __DIR__ . '/../{rel}';\n"
    )
}

/// Render the Windows `.bat` shim that runs a proxy through PHP.
pub fn render_bin_proxy_bat(tool: &str) -> String {
    format!("@ECHO OFF\r\nsetlocal DISABLEDELAYEDEXPANSION\r\n@php \"%~dp0{tool}\" %*\r\n")
}
