use serde_json::{json, Value};

/// One package's installed-state row.
pub struct InstalledPackage {
    pub name: String,
    pub version: String,
    pub package_type: String,
    pub dist_type: String,
    pub dist_url: Option<String>,
    pub reference: String,
    pub shasum: String,
    pub dev: bool,
}

const HEADER: &str = "<?php\n\n// @generated by phpm\n\n";

/// Render `vendor/composer/installed.php` — the array `Composer\InstalledVersions` loads.
/// Shape mirrors Composer 2: a `root` entry plus a `versions` map keyed by package name
/// (the root is also listed under versions).
pub fn render_installed_php(
    root_name: &str,
    root_version: &str,
    pkgs: &[InstalledPackage],
) -> String {
    let mut out = String::from(HEADER);
    out.push_str("return array(\n");
    out.push_str("    'root' => array(\n");
    out.push_str(&format!("        'name' => '{}',\n", esc(root_name)));
    out.push_str(&format!(
        "        'pretty_version' => '{}',\n",
        esc(root_version)
    ));
    out.push_str(&format!(
        "        'version' => '{}',\n",
        esc(&normalize_version(root_version))
    ));
    out.push_str("        'reference' => null,\n");
    out.push_str("        'type' => 'project',\n");
    out.push_str("        'install_path' => __DIR__ . '/../../',\n");
    out.push_str("        'aliases' => array(),\n");
    out.push_str("        'dev' => true,\n");
    out.push_str("    ),\n");
    out.push_str("    'versions' => array(\n");
    out.push_str(&render_version_row(
        root_name,
        root_version,
        "project",
        None,
        "__DIR__ . '/../../'",
        false,
    ));
    for p in pkgs {
        let install = format!("__DIR__ . '/../{}'", esc(&p.name));
        out.push_str(&render_version_row(
            &p.name,
            &p.version,
            &p.package_type,
            Some(&p.reference),
            &install,
            p.dev,
        ));
    }
    out.push_str("    ),\n");
    out.push_str(");\n");
    out
}

fn render_version_row(
    name: &str,
    version: &str,
    ptype: &str,
    reference: Option<&str>,
    install_expr: &str,
    dev: bool,
) -> String {
    let mut s = String::new();
    s.push_str(&format!("        '{}' => array(\n", esc(name)));
    s.push_str(&format!(
        "            'pretty_version' => '{}',\n",
        esc(version)
    ));
    s.push_str(&format!(
        "            'version' => '{}',\n",
        esc(&normalize_version(version))
    ));
    match reference {
        Some(r) => s.push_str(&format!("            'reference' => '{}',\n", esc(r))),
        None => s.push_str("            'reference' => null,\n"),
    }
    s.push_str(&format!("            'type' => '{}',\n", esc(ptype)));
    s.push_str(&format!(
        "            'install_path' => {},\n",
        install_expr
    ));
    s.push_str("            'aliases' => array(),\n");
    s.push_str(&format!("            'dev_requirement' => {},\n", dev));
    s.push_str("        ),\n");
    s
}

/// One package's row for installed.json, carrying its full composer.json so Composer's
/// PluginManager sees require/autoload/type/extra unchanged.
pub struct InstalledEntry {
    pub name: String,
    pub version: String,
    pub reference: String,
    pub dist_type: String,
    pub dist_url: Option<String>,
    pub shasum: String,
    pub dev: bool,
    /// The package's VCS source `{type, url, reference}`, if the lock recorded one. Composer
    /// writes this alongside `dist`; mirroring it keeps `composer dump-autoload` happy.
    pub source: Option<serde_json::Value>,
    /// The package's own composer.json, parsed. Used as the base object so require/autoload/
    /// type/extra/provide/replace flow through to Composer's PluginManager unchanged.
    pub composer_json: serde_json::Value,
}

/// Render `vendor/composer/installed.json` as a near-complete mirror of each package's own
/// composer.json. Composer's PluginManager validates plugins against this (it needs the
/// `require` block to find composer-plugin-api), so we start from the package's composer.json
/// and only overlay the install-state fields.
pub fn render_installed_json_full(entries: &[InstalledEntry]) -> String {
    let packages: Vec<Value> = entries
        .iter()
        .map(|e| {
            let mut obj = match &e.composer_json {
                Value::Object(map) => map.clone(),
                _ => serde_json::Map::new(),
            };
            obj.insert("name".into(), Value::String(e.name.clone()));
            obj.insert("version".into(), Value::String(e.version.clone()));
            obj.insert(
                "version_normalized".into(),
                Value::String(normalize_version(&e.version)),
            );
            obj.insert(
                "dist".into(),
                json!({
                    "type": e.dist_type,
                    "url": e.dist_url,
                    "reference": e.reference,
                    "shasum": e.shasum,
                }),
            );
            if let Some(src) = &e.source {
                obj.insert("source".into(), src.clone());
            }
            obj.insert("installation-source".into(), Value::String("dist".into()));
            obj.insert(
                "install-path".into(),
                Value::String(format!("../{}", e.name)),
            );
            obj.entry("type")
                .or_insert_with(|| Value::String("library".into()));
            Value::Object(obj)
        })
        .collect();
    let dev_names: Vec<&String> = entries.iter().filter(|e| e.dev).map(|e| &e.name).collect();
    let doc = json!({ "packages": packages, "dev": true, "dev-package-names": dev_names });
    serde_json::to_string_pretty(&doc).unwrap()
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

/// Composer's normalized version: numeric "X.Y.Z" → "X.Y.Z.0". Non-numeric (dev-*, +meta,
/// branches) pass through unchanged — good enough for the common semver case.
fn normalize_version(v: &str) -> String {
    let core = v.split(['-', '+']).next().unwrap_or(v);
    let parts: Vec<&str> = core.split('.').collect();
    if parts.len() == 3
        && parts
            .iter()
            .all(|p| !p.is_empty() && p.chars().all(|c| c.is_ascii_digit()))
    {
        format!("{core}.0")
    } else {
        v.to_string()
    }
}
