use serde_json::{json, Value};
use std::collections::BTreeMap;

/// One package's installed-state row.
pub struct InstalledPackage {
    pub name: String,
    pub version: String,
    pub package_type: String,
    pub reference: String,
}

const HEADER: &str = "<?php\n\n// @generated by phpm\n\n";

/// Render `vendor/composer/installed.php` — the array `Composer\InstalledVersions` loads.
/// Shape mirrors Composer 2: a `root` entry plus a `versions` map keyed by package name
/// (the root is also listed under versions).
pub fn render_installed_php(root_name: &str, root_version: &str, pkgs: &[InstalledPackage]) -> String {
    let mut out = String::from(HEADER);
    out.push_str("return array(\n");
    out.push_str("    'root' => array(\n");
    out.push_str(&format!("        'name' => '{}',\n", esc(root_name)));
    out.push_str(&format!("        'pretty_version' => '{}',\n", esc(root_version)));
    out.push_str(&format!("        'version' => '{}',\n", esc(&normalize_version(root_version))));
    out.push_str("        'reference' => null,\n");
    out.push_str("        'type' => 'project',\n");
    out.push_str("        'install_path' => __DIR__ . '/../../',\n");
    out.push_str("        'aliases' => array(),\n");
    out.push_str("        'dev' => true,\n");
    out.push_str("    ),\n");
    out.push_str("    'versions' => array(\n");
    out.push_str(&render_version_row(root_name, root_version, "project", None, "__DIR__ . '/../../'"));
    for p in pkgs {
        let install = format!("__DIR__ . '/../{}'", esc(&p.name));
        out.push_str(&render_version_row(&p.name, &p.version, &p.package_type, Some(&p.reference), &install));
    }
    out.push_str("    ),\n");
    out.push_str(");\n");
    out
}

fn render_version_row(name: &str, version: &str, ptype: &str, reference: Option<&str>, install_expr: &str) -> String {
    let mut s = String::new();
    s.push_str(&format!("        '{}' => array(\n", esc(name)));
    s.push_str(&format!("            'pretty_version' => '{}',\n", esc(version)));
    s.push_str(&format!("            'version' => '{}',\n", esc(&normalize_version(version))));
    match reference {
        Some(r) => s.push_str(&format!("            'reference' => '{}',\n", esc(r))),
        None => s.push_str("            'reference' => null,\n"),
    }
    s.push_str(&format!("            'type' => '{}',\n", esc(ptype)));
    s.push_str(&format!("            'install_path' => {},\n", install_expr));
    s.push_str("            'aliases' => array(),\n");
    s.push_str("            'dev_requirement' => false,\n");
    s.push_str("        ),\n");
    s
}

/// Render `vendor/composer/installed.json` — the package array `package:discover` reads.
/// `extras` maps package name → its composer.json `extra` value (Null if none).
pub fn render_installed_json(pkgs: &[InstalledPackage], extras: &BTreeMap<String, Value>) -> String {
    let packages: Vec<Value> = pkgs
        .iter()
        .map(|p| {
            json!({
                "name": p.name,
                "version": p.version,
                "version_normalized": normalize_version(&p.version),
                "type": p.package_type,
                "dist": { "reference": p.reference },
                "extra": extras.get(&p.name).cloned().unwrap_or(Value::Null),
            })
        })
        .collect();
    let doc = json!({ "packages": packages, "dev": true, "dev-package-names": [] });
    serde_json::to_string_pretty(&doc).unwrap()
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

/// Composer's normalized version: numeric "X.Y.Z" → "X.Y.Z.0". Non-numeric (dev-*, +meta,
/// branches) pass through unchanged — good enough for the common semver case.
fn normalize_version(v: &str) -> String {
    let core = v.split(['-', '+']).next().unwrap_or(v);
    let parts: Vec<&str> = core.split('.').collect();
    if parts.len() == 3 && parts.iter().all(|p| !p.is_empty() && p.chars().all(|c| c.is_ascii_digit())) {
        format!("{core}.0")
    } else {
        v.to_string()
    }
}
