use sha2::{Digest, Sha256};
use std::collections::BTreeMap;

const HEADER: &str = "<?php\n\n// @generated by phpm\n\n";

/// Turn a base-tagged path ("$vendorDir/foo" / "$baseDir/bar") into a PHP expression
/// like `$vendorDir . '/foo'`. A bare "$vendorDir"/"$baseDir" becomes just the variable.
fn path_expr(tagged: &str) -> String {
    for var in ["$vendorDir", "$baseDir"] {
        if let Some(rest) = tagged.strip_prefix(var) {
            if rest.is_empty() {
                return var.to_string();
            }
            return format!("{var} . '{}'", php_escape(rest));
        }
    }
    format!("'{}'", php_escape(tagged))
}

/// Escape a string for a single-quoted PHP literal (only backslash and single quote).
fn php_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

fn preamble() -> String {
    format!("{HEADER}$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n")
}

/// Render `autoload_psr4.php`: namespace prefix -> array of dirs.
pub fn render_psr4_php(psr4: &BTreeMap<String, Vec<String>>) -> String {
    render_namespace_map(psr4)
}

/// Render `autoload_namespaces.php` (PSR-0): same shape as PSR-4.
pub fn render_psr0_php(psr0: &BTreeMap<String, Vec<String>>) -> String {
    render_namespace_map(psr0)
}

fn render_namespace_map(map: &BTreeMap<String, Vec<String>>) -> String {
    let mut out = preamble();
    for (ns, dirs) in map {
        let arr = dirs.iter().map(|d| path_expr(d)).collect::<Vec<_>>().join(", ");
        out.push_str(&format!("    '{}' => array({arr}),\n", php_escape(ns)));
    }
    out.push_str(");\n");
    out
}

/// Render `autoload_files.php`: stable identifier -> file path. Keys each file by
/// sha256(path) truncated to 32 hex chars so it is required at most once.
pub fn render_files_php(files: &[String]) -> String {
    let mut out = preamble();
    for f in files {
        out.push_str(&format!("    '{}' => {},\n", file_identifier(f), path_expr(f)));
    }
    out.push_str(");\n");
    out
}

/// Render `autoload_classmap.php`: fully-qualified class name -> file path.
pub fn render_classmap_php(classmap: &BTreeMap<String, String>) -> String {
    let mut out = preamble();
    for (class, path) in classmap {
        out.push_str(&format!("    '{}' => {},\n", php_escape(class), path_expr(path)));
    }
    out.push_str(");\n");
    out
}

fn file_identifier(path: &str) -> String {
    let mut h = Sha256::new();
    h.update(path.as_bytes());
    hex::encode(h.finalize())[..32].to_string()
}

/// `vendor/autoload.php` — the entry point an app requires.
pub fn render_autoload_entry(hash: &str) -> String {
    format!(
        "<?php\n\n// @generated by phpm\n\nrequire_once __DIR__ . '/composer/autoload_real.php';\n\nreturn ComposerAutoloaderInit{hash}::getLoader();\n"
    )
}

/// `vendor/composer/autoload_real.php` — the dynamic (non-static) loader bootstrap.
/// Functionally equivalent to Composer's optimized form: it builds a ClassLoader and
/// feeds it the psr-0/psr-4/classmap arrays and the files list.
pub fn render_autoload_real(hash: &str) -> String {
    format!(
        r#"<?php

// @generated by phpm

class ComposerAutoloaderInit{hash}
{{
    private static $loader;

    public static function getLoader()
    {{
        if (null !== self::$loader) {{
            return self::$loader;
        }}

        require __DIR__ . '/ClassLoader.php';
        require __DIR__ . '/InstalledVersions.php';

        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));

        $map = require __DIR__ . '/autoload_namespaces.php';
        foreach ($map as $namespace => $path) {{
            $loader->set($namespace, $path);
        }}

        $map = require __DIR__ . '/autoload_psr4.php';
        foreach ($map as $namespace => $path) {{
            $loader->setPsr4($namespace, $path);
        }}

        $classMap = require __DIR__ . '/autoload_classmap.php';
        if ($classMap) {{
            $loader->addClassMap($classMap);
        }}

        $loader->register(true);

        $includeFiles = require __DIR__ . '/autoload_files.php';
        foreach ($includeFiles as $fileIdentifier => $file) {{
            composerRequire{hash}($fileIdentifier, $file);
        }}

        return $loader;
    }}
}}

function composerRequire{hash}($fileIdentifier, $file)
{{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {{
        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
        require $file;
    }}
}}
"#
    )
}
